// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertMedia(arg1, arg2) {
  return window['go']['main']['App']['ConvertMedia'](arg1, arg2);
}

export function InspectMedia(arg1) {
  return window['go']['main']['App']['InspectMedia'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}
