// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertMedia(arg1:string,arg2:string):Promise<main.ConversionResult>;

export function InspectMedia(arg1:string):Promise<main.MediaInfo>;

export function OpenPath(arg1:string):Promise<void>;
